/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rbgfilter;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author oguz
 */
public class MainFrame extends javax.swing.JFrame {
    
    BufferedImage img = null;
    BufferedImage filtered = null;
    File file = null;
    
    int[][] mat = null;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlContent = new javax.swing.JPanel();
        lblContent = new javax.swing.JLabel();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        pnlTools = new javax.swing.JPanel();
        sld2 = new javax.swing.JSlider();
        sld3 = new javax.swing.JSlider();
        sld1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRestore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        pnlMain.setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane1.setDividerLocation(460);

        lblContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContent.setText("Insert your picture here.");

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(lblContent, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(btnOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpen)
                    .addComponent(btnSave))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(pnlContent);

        sld2.setMaximum(255);
        sld2.setMinimum(-255);
        sld2.setOrientation(javax.swing.JSlider.VERTICAL);
        sld2.setValue(0);
        sld2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld2StateChanged(evt);
            }
        });

        sld3.setMaximum(255);
        sld3.setMinimum(-255);
        sld3.setOrientation(javax.swing.JSlider.VERTICAL);
        sld3.setValue(0);
        sld3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld3StateChanged(evt);
            }
        });

        sld1.setMaximum(255);
        sld1.setMinimum(-255);
        sld1.setOrientation(javax.swing.JSlider.VERTICAL);
        sld1.setValue(0);
        sld1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld1StateChanged(evt);
            }
        });

        jLabel1.setText("Red");

        jLabel2.setText("Green");

        jLabel4.setText("Blue");

        btnRestore.setText("Restore");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlToolsLayout = new javax.swing.GroupLayout(pnlTools);
        pnlTools.setLayout(pnlToolsLayout);
        pnlToolsLayout.setHorizontalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlToolsLayout.createSequentialGroup()
                        .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addComponent(sld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addComponent(sld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sld3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlToolsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRestore)))
                .addContainerGap())
        );
        pnlToolsLayout.setVerticalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sld1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sld2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sld3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestore)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(pnlTools);

        pnlMain.add(jSplitPane1);

        getContentPane().add(pnlMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fchooser = new JFileChooser();
       
        int returnValue = fchooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            file = fchooser.getSelectedFile();
            try {
                img = ImageIO.read(file);
                filtered = img;
                ImageIcon ic = new ImageIcon(img);
                lblContent.setIcon(ic);
                lblContent.setText("");
                repaint();
            } catch (IOException ex) {
                lblContent.setText("This file doesn't look like a valid file please try another!");
                repaint();
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed
    private void getRGBfromImage() throws IOException{
        img = ImageIO.read(file);
        if(img!=null){
            int w = img.getWidth();
            int h = img.getHeight();
                mat = new int[h][w];
                for(int row = 0;row < h;row++){
                    for(int col = 0;col < w;col++){
                        mat[row][col] = img.getRGB(col, row);
                    }
                }   
        }
    }
    private void filterRGB(int r,int g,int b) throws IOException{
         getRGBfromImage();
        if(img!=null && mat!=null){
           
            int w = img.getWidth();
            int h = img.getHeight();
            Color res = null;
            for(int row = 0;row < h;row++){
                    for(int col = 0;col < w;col++){
                        Color c = new Color(mat[row][col]);
                        
                        int red = c.getRed();
                        int green = c.getGreen();
                        int blue = c.getBlue();
                        
                        red+=r;
                            if(red>255) red = 255;
                            else if(red<0) red = 0;
                        green+=g;
                            if(green>255) green = 255;
                            else if(green<0) green = 0;
                        blue+=b;
                            if(blue>255) blue = 255;
                            else if(blue<0) blue = 0;
                            
                        res = new Color(red, green, blue);
                        mat[row][col] = res.getRGB();                       
                    }                
                }
            setImageFiltered();
        }
    }
    
    private void setImageFiltered(){
        if(mat!=null){
            int h = img.getHeight();
            int w = img.getWidth();
                for(int row = 0;row < h;row++){
                    for(int col = 0;col < w;col++){
                       filtered.setRGB(col, row, mat[row][col]);
                    }
                }   
        }
    }
    
    private void sld1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld1StateChanged
        // TODO add your handling code here:
        
        if(!sld1.getValueIsAdjusting()){
            try {    
                filterRGB(sld1.getValue(), sld2.getValue(), sld3.getValue());
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        repaint();
        }
    }//GEN-LAST:event_sld1StateChanged

    private void sld2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld2StateChanged
        // TODO add your handling code here:
           
        if(!sld2.getValueIsAdjusting()){
            try {    
                filterRGB(sld1.getValue(), sld2.getValue(), sld3.getValue());
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        repaint();
        }
    }//GEN-LAST:event_sld2StateChanged

    private void sld3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld3StateChanged
        // TODO add your handling code here:
           
        if(!sld3.getValueIsAdjusting()){
            try {    
                filterRGB(sld1.getValue(), sld2.getValue(), sld3.getValue());
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        repaint();
        }
    }//GEN-LAST:event_sld3StateChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        JFileChooser fchooser = new JFileChooser();
        fchooser.setSelectedFile(new File(file.getName().replaceFirst("[.][^.]+$", "")+"-filtered.png"));
        int returnValue = fchooser.showSaveDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File output = fchooser.getSelectedFile();
            try {
                ImageIO.write(filtered, "png", output);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
       
            sld1.setValue(0);
            sld2.setValue(0);
            sld3.setValue(0);

            if(img!=null){
                try {
                    filterRGB(sld1.getValue(), sld2.getValue(), sld3.getValue());
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
    }//GEN-LAST:event_btnRestoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblContent;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTools;
    private javax.swing.JSlider sld1;
    private javax.swing.JSlider sld2;
    private javax.swing.JSlider sld3;
    // End of variables declaration//GEN-END:variables
}
